version: 2.1
dependencies:
  pre:
    - sudo apt-get install apt -y
    - sudo add-apt-repository ppa:beineri/opt-qt542-trusty -y
    - sudo apt-get update -y; true
    - sudo apt-get install -y qt54webkit libwebkit-dev libgstreamer0.10-dev
    - echo "/opt/qt54/bin/qt54-env.sh" >> ~/.circlerc
  environment:
    QMAKE: /opt/qt54/bin/qmake
jobs:
  build:
    docker: 
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: qmake -config release
      - run: make
      - run: make clean
      - run: ./LogicGateCalculator

